Wordle
hcp-uw/cool-husky-games pull request #9
Opened 2024-05-06 01:35 UTC by aadityathukral

Pull branch after I messed up Wordle 💀 (sorry Justin). 

Added some stylistic changes to Wordle, will update further.

2024-05-06 01:40 UTC, mjh316 requested changes

2024-05-06 01:40 UTC, mjh316 commented on public/uploads/wordle/wordguesser.js
> +    console.log(letter);
What's this for?

2024-05-06 01:48 UTC, aadityathukral commented on public/uploads/wordle/wordguesser.js
> +    console.log(letter);
Oh shit, that was for debugging purposes, I'll get rid of it the next time I commit some more changes

2024-05-06 04:42 UTC, mjh316 approved these changes
LGTM!

2024-05-06 04:43 UTC, mjh316 commented on public/uploads/wordle/wordguesser.js
> +    console.log(letter);
Alright, I'll go ahead and comment it out for now

2024-05-06 04:45 UTC, mjh316 commented
@don-mo , what do you think? (meant to tag above but forgot)

2024-05-06 20:13 UTC, don-mo requested changes
# Nice! 
### Maybe these changes as well
 - display: none; for the title tag
 
 - doesn't have to be for right now but creating an animation would be dope haaha
![wordle_example](https://github.com/hcp-uw/cool-husky-games/assets/139363584/516d1bca-a168-4bcb-88aa-5a957cfcf2b9)

2024-05-09 07:46 UTC, mjh316 commented
@aadityathukral

2024-05-12 02:05 UTC, aadityathukral commented
Hey @mjh316, Siddharth wanted to get up to date with the changes I've made so far as well, is there a way to do that or would this branch need to be merged first?

2024-05-12 19:30 UTC, don-mo commented
@aadityathukral Ok, to let @sidlak-c137 get caught up with the work that's been created this is good!! Sorry, codeacademy told me that this is how GitHub collaboration works, but I'm still getting used to it :))

2024-05-12 19:31 UTC, don-mo reviewed
# Merging 👍 
For @sidlak-c137 to get caught up!!

2024-05-12 19:34 UTC, don-mo approved these changes

2024-05-12 19:36 UTC, merged